sudo: required
dist: trusty
language: python
git:
  depth: 10
  quiet: true
python:
  - "3.6"
env:
  matrix:
    - PROJECT="adversarial_robustness"
    # - PROJECT="cs_gan"  # TODO(b/184845450): Fix and re-enable
    - PROJECT="gated_linear_networks"
    - PROJECT="geomancer"
    - PROJECT="hierarchical_probabilistic_unet"
    - PROJECT="iodine"
    - PROJECT="kfac_ferminet_alpha"
    - PROJECT="learning_to_simulate"
    - PROJECT="nfnets"
    - PROJECT="option_keyboard"
    # - PROJECT="polygen"  # TODO(b/184847339): Fix and re-enable
    # - PROJECT="scratchgan"  # TODO(b/184856293): Fix and enable
    - PROJECT="sketchy"
    - PROJECT="transporter"
    - PROJECT="tvt"
    # - PROJECT="unrestricted_advx"  # TODO(b/184862249): Fix and enable
    - PROJECT="unsupervised_adversarial_training"
    - PROJECT="meshgraphnets"
before_script:
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
  - pip install --upgrade wheel
script:
  - ./$PROJECT/run.sh

